spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      password:

clients:
  jsonplaceholder:
    base-url: https://jsonplaceholder.typicode.com
