### Account API

@host = http://localhost:1009

### Register a new user
POST {{host}}/api/account/register
Content-Type: application/json

{
  "username": "testuser",
  "nickname": "테스터",
  "email": "test@example.com",
  "password": "testpassword"
}

> {%
    client.global.set("username", response.body.username);
%}

### Login and Get Token
POST {{host}}/api/account/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Get User Info
GET {{host}}/api/account/me
Authorization: Bearer {{auth_token}}
