### Create User
POST {{host}}/api/v1/users
Content-Type: application/json

{
  "name": "Master User",
  "email": "master@example.com"
}

> {%
    client.global.set("tx-user-id", response.body['id']);
%}

### Find User By ID
GET {{host}}/api/v1/users/{{tx-user-id}}
Content-Type: application/json

### Update User
PUT {{host}}/api/v1/users/{{tx-user-id}}
Content-Type: application/json

{
  "name": "Updated User"
}

### Delete User
DELETE {{host}}/api/v1/users/{{tx-user-id}}
